Return diagnostics table with each level count (errors, warnings and info) for the diagnostics_indicator
akinsho/nvim-bufferline.lua pull request #67
Opened 2021-03-25 06:14 UTC by arsaniwilliam

Return a dictionary of error level and number of errors for each level.
It's backwards compatible and should allow for a custom diagnostic count such as this:
 ```lua
 config = {
  ....
  diagnostics_indicator = function(_, _, x)
      local s = " "
      for e, n in pairs(x) do
        local sym = e == 1 and " " or (e == 2 and " " or "" )
        s = s .. n .. sym
      end
      return s
    end,
....
}
```
<img width="1091" alt="Screen Shot 2021-03-24 at 11 12 36 PM" src="https://user-images.githubusercontent.com/4028913/112427204-6dfbe400-8cf6-11eb-97e5-d224a4099edc.png">
<img width="1087" alt="Screen Shot 2021-03-24 at 11 11 53 PM" src="https://user-images.githubusercontent.com/4028913/112427155-5ae91400-8cf6-11eb-9f2d-dbcea2fa87ad.png">
<img width="1053" alt="Screen Shot 2021-03-24 at 11 00 47 PM" src="https://user-images.githubusercontent.com/4028913/112426295-f37e9480-8cf4-11eb-8912-47c24ceec0a1.png">

P.S. this is my first experience writing Lua, and thank you for the great plugin!

2021-03-25 06:22 UTC, arsaniwilliam commented
sorry didn't squash the commits before the pr.

2021-03-25 09:31 UTC, akinsho requested changes
@arsaniwilliam thanks for the PR this looks good in general. I've made a couple of comments re. casing and formatting. Sorry this project doesn't have an autoformatter in CI or something so it's not clear what the rules are 😓 .

Also I think it'd be good to update the documentation and the README so other people know what is now possible. Maybe you can include some of your screenshots as well so people can get some inspiration 👍🏿

2021-03-25 09:31 UTC, akinsho commented on lua/bufferline/diagnostics.lua
> +local function getErrDict (errs)
the convention in lua is to use snake case for identifiers so this should be `get_err_dict`

2021-03-25 09:31 UTC, akinsho commented on lua/bufferline/diagnostics.lua
> +  local maxSev = max==1 and "error" or (max==2 and "warning" or "info")
similar issue as above i.e. snake_case_here

2021-03-25 09:31 UTC, akinsho commented on lua/bufferline/diagnostics.lua
> +      if ds[s]
could you reformat this to be
```lua
if ds[s] then
  ds[s] = ds[s] + 1
else
  ds[s] = 1
end
```

2021-03-25 09:31 UTC, akinsho commented on lua/bufferline/diagnostics.lua
> +    result[buf_num] = { count = #items,
sorry more formatting issues, can you change the indent level here so it looks more like it did previously i.e.
```lua
result[buf_num] = {
  count = #items,
  level = d.level,
  errors = d.errors
}
```

2021-03-26 03:37 UTC, arsaniwilliam commented
@akinsho Thank you for the suggestions!
I made the changes you requested, and updated the Readme.

2021-03-26 16:44 UTC, akinsho commented
@arsaniwilliam thanks for making the changes, will have a look shortly just a bit busy at the moment but should be free in a little bit

2021-03-26 16:59 UTC, akinsho commented on lua/bufferline/diagnostics.lua
> +      if ds[s] then
@arsaniwilliam I only just noticed/thought of this now but could the structure of this table map to the type of error so that at a glance the object is more legible so users don't have to dig into what `1`,`2` and `3` mean i.e.
```lua
{
 error = 2,
 warning = 0,
 info = 1,
}
```
you could keep an internal mapping of level number to error type rather than exposing the numbers to users which I think is a little less user friendly? WDYT?

2021-03-26 17:00 UTC, akinsho commented on lua/bufferline/diagnostics.lua
> +      if ds[s] then
so basically each object would alway have all three fields but the value related to each type would be the thing that changed.

2021-03-27 16:16 UTC, akinsho commented on lua/bufferline/diagnostics.lua
> +      if ds[s] then
@arsaniwilliam WDYT?

2021-03-30 04:20 UTC, arsaniwilliam commented on lua/bufferline/diagnostics.lua
> +      if ds[s] then
you're right - it's probably more user friendly to return a dict from err_level to count
example: ```lua
{ "error" =3 ,
  "warning" = 5,
  "info" = 2 
}
```
The last commit takes care of that. i'll update the Readme too.

2021-03-30 07:38 UTC, merged

2021-03-30 07:38 UTC, akinsho commented
This looks good to merge now @arsaniwilliam thanks for all your work on this 👍🏿