Added new mode 'mix'
akinsho/nvim-bufferline.lua pull request #70
Opened 2021-04-01 01:25 UTC by jerrywang1981

1. in the new mode 'mix', it will be like lightline-bufferline, with both
   ordinal number and buffer id available.
2. number_style will not work in new mode 'mix'

2021-04-01 08:39 UTC, akinsho requested changes
Thanks for the PR @jerrywang1981, I've left some comments about naming stuff and formatting, but slightly more importantly I think the current way the numbers are laid out is a little confusing. I think there must be a better way to show them maybe something like `1.) filename.js ²` or something

2021-04-01 08:39 UTC, akinsho commented on README.md
> +    numbers = "none" | "ordinal" | "buffer_id" | "mix",
I'd prefer if the new name was `both` not mix. Mix is a little confusing

2021-04-01 08:39 UTC, akinsho commented on doc/bufferline-lua.txt
> +            numbers = "none" | "ordinal" | "buffer_id" | "mix",
Same here re. naming this `both`

2021-04-01 08:39 UTC, akinsho commented on lua/bufferline/numbers.lua
> +local t_numbers = { ['0'] = "⁰", ['1'] = "¹", ['2'] = "²", ['3'] = "³", ['4'] = "⁴", ['5'] = "⁵", ['6'] = "⁶", ['7'] = "⁷", ['8'] = "⁸", ['9'] = "⁹" }
Can you please collapse this table into multiple lines? same as the one below.
I also think they should be named more clearly. `t_numbers` is actually `superscript_numbers`
and the one below `d_numbers` is `subscript_numbers`

2021-04-01 08:39 UTC, akinsho commented on lua/bufferline/numbers.lua
> +local trans_number = function (t, n)
I'd rename this function to `convert_to_styled_num` or something that explains what it does

2021-04-01 08:39 UTC, akinsho commented on lua/bufferline/numbers.lua
> +    return trans_number(t_numbers, buffer.id) .. trans_number(d_numbers, buffer.ordinal)
The current appearance of this new mode is *quite* confusing, I think to adjacent superscipt and subscript numbers is not really very clear UI, which is which? how does the user know?

![image](https://user-images.githubusercontent.com/22454918/113266958-b8202f00-92cd-11eb-828d-985ad326bcdf.png)

2021-04-01 12:59 UTC, jerrywang1981 commented on README.md
> +    numbers = "none" | "ordinal" | "buffer_id" | "mix",
done

2021-04-01 12:59 UTC, jerrywang1981 commented on doc/bufferline-lua.txt
> +            numbers = "none" | "ordinal" | "buffer_id" | "mix",
done

2021-04-01 12:59 UTC, jerrywang1981 commented on lua/bufferline/numbers.lua
> +local t_numbers = { ['0'] = "⁰", ['1'] = "¹", ['2'] = "²", ['3'] = "³", ['4'] = "⁴", ['5'] = "⁵", ['6'] = "⁶", ['7'] = "⁷", ['8'] = "⁸", ['9'] = "⁹" }
done

2021-04-01 12:59 UTC, jerrywang1981 commented on lua/bufferline/numbers.lua
> +local trans_number = function (t, n)
done

2021-04-01 13:02 UTC, jerrywang1981 commented on lua/bufferline/numbers.lua
> +    return trans_number(t_numbers, buffer.id) .. trans_number(d_numbers, buffer.ordinal)
it might be confusing at first look, but with good documentation it will not be problem, and this is how lightline-bufferline looks like with buffer id at left and ordinal number at right. keeping same design might be good to lightline-bufferline users.

screenshot from my previous `lightline-bufferline`
![image](https://user-images.githubusercontent.com/8133242/113297708-89d23c00-932d-11eb-8493-210f99a0ee11.png)

2021-04-01 13:32 UTC, akinsho commented on lua/bufferline/numbers.lua
> +    return trans_number(t_numbers, buffer.id) .. trans_number(d_numbers, buffer.ordinal)
I prefer the lightline bufferline look to what this PR currently uses which is a mixture of super and subscript numbers. I think it might be nice to still offer the user the option of specifying a style for each type. So maybe when mode is set to `both` then you can specify

```lua
number_style = {id = "superscript", ordinal = "subscript" | "none" | "period" }
-- in numbers.lua
if type(number_style) == "table" and mode == "both" then
  -- apply the right style per section
end
```

So it will be customisable for users. I think the default should be like the screenshot you have above. I don't really like it tbh but I don't use numbers and as long as other users can customise it I'm fine. I think this also needs adding to the docs in help. And maybe a screenshot in the readme with an explanation as well.

2021-04-01 13:35 UTC, akinsho commented on lua/bufferline/numbers.lua
> +    return trans_number(t_numbers, buffer.id) .. trans_number(d_numbers, buffer.ordinal)
None can be a full sized number and period `4.` addition of a period to a number

2021-04-02 03:50 UTC, jerrywang1981 commented on lua/bufferline/numbers.lua
> +    return trans_number(t_numbers, buffer.id) .. trans_number(d_numbers, buffer.ordinal)
not sure where to put the screenshot.

default:
<img width="657" alt="Screen Shot 2021-04-02 at 10 58 12 AM" src="https://user-images.githubusercontent.com/8133242/113378393-7fee1e80-93a9-11eb-9797-da1a5a5716cc.png">

with 
```
number_style = { "superscript", "subscript"}
```
<img width="636" alt="Screen Shot 2021-04-02 at 11 38 51 AM" src="https://user-images.githubusercontent.com/8133242/113378443-9e541a00-93a9-11eb-8e1b-6fa28c2bb475.png">

2021-04-02 08:30 UTC, akinsho commented on lua/bufferline/numbers.lua
> +    return trans_number(t_numbers, buffer.id) .. trans_number(d_numbers, buffer.ordinal)
👍🏾 this looks great, thanks for tweaking it. Regarding the screenshot you can copy the link from this issue comment and reuse it in the readme.

Or better still there's a closed issue called screenshots where I stash them all. If you post it there and reuse the link then I'll be able to find it better in the future.

2021-04-02 09:02 UTC, jerrywang1981 commented on lua/bufferline/numbers.lua
> +    return trans_number(t_numbers, buffer.id) .. trans_number(d_numbers, buffer.ordinal)
updated readme

2021-04-02 09:20 UTC, akinsho commented on lua/bufferline/numbers.lua
> +      -- return convert_to_styled_num(superscript_numbers, buffer.id) .. convert_to_styled_num(subscript_numbers, buffer.ordinal)
@jerrywang1981 looks like this line is left over now , if you just want to skip updating the `both_style` for you can combine the inverse of the this condition with the one below like.
```lua
	if style ~= "superscript" and type(style) == "table" then
     -- both style updates
    end
```

2021-04-02 09:40 UTC, akinsho commented
Just tried this out locally, thanks for tweaking the number style option. It doesn't seem to work in all cases though. I tried `number_style = {"none", "none"} that doesn't give `1. 2.` also tried `{"superscript", "none"}` and that just gives `1.` no super script number

2021-04-02 10:16 UTC, jerrywang1981 commented
> Just tried this out locally, thanks for tweaking the number style option. It doesn't seem to work in all cases though. I tried `number_style = {"none", "none"} that doesn't give `1. 2.`also tried`{"superscript", "none"}`and that just gives`1.` no super script number

you were right, just fixed  it.

2021-04-02 11:47 UTC, akinsho approved these changes
Alright this looks fine to merge now @jerrywang1981 👍🏿

2021-04-02 11:47 UTC, merged